[build-system]
requires = ["hatchling", "hatch-requirements-txt"]
build-backend = "hatchling.build"

[project]
name = "mTree"
dynamic = ["version", "dependencies",]
requires-python = ">=3.10"
authors = [
  {name = "GMU CEELAB", email = "mtree.email@gmail.com"}
]
maintainers = [
  {name = "GMU CEELAB", email = "mtree.email@gmail.com"}
]
description = "The mTree Computational Microeconomics Package"
readme = "README.md"
license = "MIT"
keywords = ["computational experimental economics"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]

[tool.hatch.metadata.hooks.requirements_txt]
files = ["./requirements/base.txt"]

[tool.hatch.version]
path = "mTree/version.py"

[project.urls]
Homepage = "https://mtree.readthedocs.io/"
Documentation = "https://mtree.readthedocs.io/"
Repository = "https://github.com/gmucsn/mTree"
"Bug Tracker" = "https://github.com/gmucsn/mTree/issues"
Changelog = "https://github.com/gmucsn/mTree/master/CHANGELOG.md"

[project.scripts]
mTree_developer_server = "mTree.scripts.mTree_developer_server:main"
mTree_runner = "mTree.utilities.mTree_runner:app"
mTree_console = "mTree.utilities.mtree_console:main"
mTree_cli = "mTree.utilities.mtree_cli:app"

[tool.towncrier]
# package = "mTree"
directory = "changes"
filename = "CHANGELOG.md"

[tool.bumpversion]
current_version = "2.0.1-dev0"
parse = """(?x)
    (?P<major>0|[1-9]\\d*)\\.
    (?P<minor>0|[1-9]\\d*)\\.
    (?P<patch>0|[1-9]\\d*)
    (?:
        -                             # dash seperator for pre-release section
        (?P<pre_l>[a-zA-Z-]+)         # pre-release label
        (?P<pre_n>0|[1-9]\\d*)        # pre-release version number
    )?                                # pre-release section is optional
"""
serialize = [
    "{major}.{minor}.{patch}-{pre_l}{pre_n}",
    "{major}.{minor}.{patch}",
]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
ignore_missing_files = false
tag = false
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = false
commit = false
message = "Bump version: {current_version} → {new_version}"
commit_args = ""

[tool.bumpversion.parts.pre_l]
values = ["dev", "rc", "final"]
optional_value = "final"

[[tool.bumpversion.files]]
filename = 'mTree/version.py'
search = "__date__ = '\\d{{4}}-\\d{{2}}-\\d{{2}}'"
replace = "__date__ = '{now:%Y-%m-%d}'"
regex = true

[[tool.bumpversion.files]]
filename = "mTree/version.py"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests"
]

[tool.isort]
profile = "hug"
src_paths = ["isort", "test"]
float_to_top = true

[tool.black]
line-length = 88
target-version = ['py313']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/foo.py    # exclude a file named foo.py in the root of the project
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''