agents:
- agent_name: basic_auction_agent.BasicAuctionAgent
  class_name: ''
  number: 4
  properties:
    strategy: reasonable
- agent_name: basic_auction_agent.BasicAuctionAgent
  class_name: ''
  number: 4
  properties:
    strategy: aggressive
data_logging: json
debug: true
environment:
  mes_class: basic_auction_environment.AuctionEnvironment
  name: basic_auction_institution.AuctionInstitution
  properties: {}
file_source: 
  /workspaces/mTree/examples/human_subject_experiments/config/basic_auction_simulation.json
id: '1'
institutions:
- class_name: basic_auction_institution.AuctionInstitution
  institution_name: basic_auction_institution.AuctionInstitution
  properties: {}
log_level: 2
mes_directory: /workspaces/mTree/examples/human_subject_experiments
mtree_type: mes_simulation_description
name: Basic Auction Simulation
number_of_iterations: 1
properties: {}
simulation_run_id: ''
source_hash: ''
